# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'pypy3'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi


jobs:
  allow_failures:
    - arch: arm64
  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9'
      arch: arm64
    - python: 'pypy3'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.7"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/repo_helper
        provider: pypi
        user: "DomDF"
        password:
          secure: aB17VofHqBsFpQFeEvXov5FuQh4bKtuZ4w3pUqfNS472bJJJcYXefog3sEYRZRxnmltxJv8OA8qp7ZvH4pjtQ0w4S9J96vm/5aTySBkIkJrCQK5OCHgCAqwM2Im0QbB34ih2hHDdJ7b65j2HcEvfj9k3OsUueRy1UKelPYPwB3gJLfZXJtXqrwF9vDbj8a245DgOGEhIeD2f6kMH9ETE8sZvi8hJgZjmhDY613ToXAZBFJgcjn4zE3GHBHSpipaQCtwGtxiWwfTfDrZqpgQcgv/eKEybKTavto5txBnSCFFZe5LUb2na3RJwktN9DWoy3C9RIRtHHcaxFQAGR8zCTtSHk5oLQVwrKOOmezKk4+DynupbfDkY94MSDK9NqJu/fYHY3qft5fKGH0a9zqIX6MEG8HFlI217DOIySpyEoApatDUu+6TGqwt/FbSOADOjNNWz72ihF6EtFcdHHon8RV7gx+k513802cdU18YlhlCLoRiH/N2ZL5nOreG0m+kZ9beZTRxL+ITxh0WeKIBSBUPfAp/6ZtmKztlOGaZpEbpxTM1aTI0hLOJ5pk/hxJFRPZseFhVV0d974XxnaSFzmPKz5jUNjCafU3JVry1Ac0B1/AHs9/zZy8mwCIsRmM3gTkVG0U3lBAv7JRpPMZVGRJMYI7fjJ1YkIY/CiYf2SvA=
        distributions: "sdist bdist_wheel"
        skip_existing: true
